# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nome da palestra.', max_length=100, verbose_name='title')),
                ('date', models.DateTimeField(unique=True, verbose_name='lecture_date')),
                ('equipment', models.CharField(blank=True, max_length=100, null=True, verbose_name='equipments')),
                ('description', models.TextField(default='', help_text='Descrição da palestra', max_length=200, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='MiniCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies', models.IntegerField(verbose_name='vacancies')),
                ('enrolled', models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seccim_app.Lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Seccim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='número romano da edição da seccim', max_length=5, verbose_name='version')),
                ('is_active', models.BooleanField(help_text='deve haver somente um ativa', verbose_name='is_active')),
                ('start_date', models.DateTimeField(blank=True, help_text='inicio do evento', null=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(blank=True, help_text='fim do evento', null=True, verbose_name='end_date')),
                ('year', models.IntegerField(help_text='ano', verbose_name='year')),
                ('mini_course_vacancies', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nome do autor.', max_length=50)),
                ('origin', models.CharField(blank=True, help_text='Empresa ou instituição do palestrante.', max_length=50, null=True)),
                ('twitter', models.CharField(blank=True, help_text='link do twitter.', max_length=50, null=True)),
                ('facebook', models.CharField(blank=True, help_text='link do facebook.', max_length=50, null=True)),
                ('linkedin', models.CharField(blank=True, help_text='link do linkedin.', max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('car_plate', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(help_text='Descriçao breve do palestrante', max_length=1000)),
                ('seccim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seccim_app.Seccim')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='seccim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seccim_app.Seccim'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seccim_app.Speaker'),
        ),
    ]
