# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarathonTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30, verbose_name='nick')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('telephone', models.CharField(max_length=15, verbose_name='telephone')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=9, verbose_name='gender')),
                ('schooling', models.CharField(choices=[('0', '0'), ('1', 'Ensino Fundamental'), ('2', 'Ensino Medio'), ('3', 'Superior incompleto'), ('4', 'Superior completo'), ('5', 'Pos-graduado'), ('6', 'Mestrado'), ('7', 'Doutorado')], default='0', max_length=1, verbose_name='schooling')),
                ('course', models.CharField(max_length=50, verbose_name='course')),
                ('institution', models.CharField(max_length=50, verbose_name='institution')),
                ('period', models.CharField(max_length=20, verbose_name='period')),
                ('payed', models.BooleanField(default=False, verbose_name='payed')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.MarathonTeam')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
